"""Analyse as a periodic report writer.

Analyse refreshes a "state of the run" report (narrative header + data
sections) as a VIEW of the tree — overwritten in place, never a record.
Writing the report must not create an attempt.
"""

import tempfile
from pathlib import Path

from groundhog import Analyse, MarkdownLearnings, Task, Toolkit
from groundhog.backends.mock import MockBackend
from groundhog.base.backend import BackendRegistry
from groundhog.base.types import (
    Context, Data, EvalStage, Evaluator, StageResult,
)
from groundhog.histories.folder import FolderAttemptHistory


class _Data(Data):
    def get_train(self):
        return None

    def get_test(self):
        return None


class _Ctx(Context):
    def get_brief(self):
        return "Write solve() returning a float."

    def get_extended(self):
        return "def solve() -> float"


class _Eval(Evaluator):
    def evaluate(self, code_or_path, data):
        if isinstance(code_or_path, (str, bytes)):
            code = code_or_path
        else:
            code = (Path(code_or_path) / "solution.py").read_text(encoding="utf-8")
        ns = {}
        try:
            exec(code, ns)
            value = float(ns["solve"]())
        except Exception as e:
            return StageResult(errors={"crash": str(e)})
        return StageResult(metrics={"value": value})

    def get_stages(self, data):
        return [
            EvalStage("eval", "eval",
                      lambda cp, d=data: self.evaluate(cp, d),
                      scorer=lambda r: -1.0 if r.errors
                      else r.metrics.get("value", 0.0) / 100.0),
        ]


def _task():
    return Task(data=_Data(), context=_Ctx(), evaluator=_Eval(), name="t")


def _code(value):
    return f"def solve():\n    return {value}"


def _commit_root(history, task, value, direction=None):
    from groundhog.utils.direction import write_direction
    from groundhog.utils.results import write_result
    ws = history.workspace()
    (ws.path / "solution.py").write_text(_code(value), encoding="utf-8")
    if direction:
        write_direction(ws.path, direction)
    write_result(ws.path, task.evaluate(_code(value)))
    return ws.commit(success=True)


def _toolkit(tmp, responses=("narrative text",)):
    history = FolderAttemptHistory(Path(tmp))
    task = _task()
    toolkit = Toolkit(task=task, history=history, path=Path(tmp))
    toolkit.llm = BackendRegistry(default=MockBackend(list(responses)))
    toolkit.learnings = MarkdownLearnings(Path(tmp))
    return toolkit, history, task


def test_report_written_with_sections():
    with tempfile.TemporaryDirectory() as tmp:
        toolkit, history, task = _toolkit(tmp)
        _commit_root(history, task, 70.0, direction="rollout")
        _commit_root(history, task, 30.0, direction="mcts")
        toolkit.learnings.add("rollout beats mcts so far")

        out = Analyse()(toolkit)

        report = Path(tmp) / "reports" / "state.md"
        assert report.exists()
        assert out["report"] == str(report)
        text = report.read_text(encoding="utf-8")
        for section in ("# State of the run", "narrative text", "## Summary",
                        "## Families", "## Last", "## Top learnings",
                        "generated by analyse at"):
            assert section in text
        # Data made it into the sections.
        assert "rollout" in text and "mcts" in text
        assert "0.7000" in text  # best score of the value=70 attempt


def test_report_refreshed_in_place():
    with tempfile.TemporaryDirectory() as tmp:
        toolkit, history, task = _toolkit(tmp, responses=["first pass"])
        _commit_root(history, task, 70.0, direction="rollout")
        Analyse()(toolkit)

        report = Path(tmp) / "reports" / "state.md"
        first = report.read_text(encoding="utf-8")
        assert "first pass" in first

        # New narrative, run again — file is overwritten, not appended.
        toolkit.llm = BackendRegistry(default=MockBackend(["second pass"]))
        Analyse()(toolkit)
        second = report.read_text(encoding="utf-8")
        assert "second pass" in second
        assert "first pass" not in second
        assert second.count("# State of the run") == 1


def test_report_writing_creates_no_attempt():
    with tempfile.TemporaryDirectory() as tmp:
        toolkit, history, task = _toolkit(tmp)
        _commit_root(history, task, 70.0, direction="rollout")
        toolkit.learnings.add("something")

        before = len(history.list(only_done=False))
        Analyse()(toolkit)
        after = len(history.list(only_done=False))
        assert before == after


def test_write_report_false_skips_file():
    with tempfile.TemporaryDirectory() as tmp:
        toolkit, history, task = _toolkit(tmp)
        _commit_root(history, task, 70.0, direction="rollout")
        toolkit.learnings.add("something")

        out = Analyse(write_report=False)(toolkit)
        assert "report" not in out
        assert not (Path(tmp) / "reports" / "state.md").exists()


def test_report_written_before_any_learnings():
    with tempfile.TemporaryDirectory() as tmp:
        toolkit, history, task = _toolkit(tmp)
        _commit_root(history, task, 40.0, direction="rollout")

        out = Analyse()(toolkit)  # no learnings added
        report = Path(tmp) / "reports" / "state.md"
        assert report.exists()
        assert out["entries_before"] == 0
        assert "_(none yet)_" in report.read_text(encoding="utf-8")
